force-app/main/default/objects/Flow_Upsert__e/Flow_Upsert__e.object-meta.xml
<CustomObject>
    <label>Flow Upsert</label>
    <pluralLabel>Flow Upserts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Flow_Upsert__e/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flow_Upsert__e/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Upsert__e/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Flow_Upsert__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_Upsert__e/fields/Total_Records__c.field-meta.xml
<CustomField>
    <fullName>Total_Records__c</fullName>
    <label>Total Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpsertRecordsFlowAction.cls
public class UpsertRecordsFlowAction {
    
    @InvocableMethod(label='Bulk Upsert Tool'
    description='Allows you to upsert data to an object in salesforce using Async Future Batches for performance' 
    iconName='slds:standard:data_streams') 
public static void upsertRecords(List<UpsertDetailsRequest> wrappers) {
    List<UpsertDetailsResultForFlow> resultsToReturn = new List<UpsertDetailsResultForFlow>();
    for(UpsertDetailsRequest wrapper : wrappers) {
        system.debug(wrapper.batchSize);
        system.debug(wrapper.upsertFieldName);
        List<UpsertDetailsResultForFlow> results = doWork(wrapper);
        resultsToReturn.addAll(results);
    }
    // return resultsToReturn;
}
    
    private static List<UpsertDetailsResultForFlow> doWork(UpsertDetailsRequest wrapper){
        // Adding a section for test coverage of very large data sets
        Boolean RunLargeTestDetails = false;
        
        List<SObject> recordsToUpsert = new List<SObject>();
        List<UpsertDetailsResultForFlow> returnResult = new List<UpsertDetailsResultForFlow>();
        UpsertDetailsResultForFlow invocableResult = new UpsertDetailsResultForFlow();
        String upsertFieldName = '';
        Integer batchSize = 0;
        invocableResult.isSuccessful = false;
        
            
            // Adding a section for test coverage of very large data sets
            if(Test.isRunningTest()) {
                if (wrapper.records.size() == 1234) {
                    RunLargeTestDetails = true;
                }
            }
            
            upsertFieldName = wrapper.upsertFieldName;
            batchSize = wrapper.BatchSize;
            Integer adjustedBatchSize = 0;
            
            Integer totalRecords = wrapper.records.size();
            Integer futureCallsNeeded = (Integer)Math.ceil(totalRecords / (Decimal)batchSize);
            Integer maxFutureCalls = 50; // Salesforce limit
            
            // If the number of future calls needed exceeds the max limit, adjust the batch size
            if (futureCallsNeeded > maxFutureCalls || RunLargeTestDetails == true) {
                adjustedBatchSize = (Integer)Math.ceil(totalRecords / (Decimal)maxFutureCalls);
            } else {
                // If within the limit, use the specified batch size or the total number of records if less
                adjustedBatchSize = Math.min(batchSize, totalRecords);
            }
            invocableResult.TotalRecords = totalRecords;
            invocableResult.ActualBatchSize = adjustedBatchSize;
            invocableResult.NumberOfBatches = (Integer)Math.ceil((Decimal)wrapper.records.size() / (Decimal)adjustedBatchSize);
            system.debug(invocableResult);
            if (adjustedBatchSize > 10000 || RunLargeTestDetails == true) {
                invocableResult.isSuccessful = false;
                invocableResult.ErrorMessage = 'Batch size is too large for upsert operation';
            } else {
                for (SObject record : wrapper.records) {
                    recordsToUpsert.add(record);
                    
                    if (recordsToUpsert.size() == adjustedBatchSize) {
                        upsertRecordsAsync(JSON.serialize(recordsToUpsert), upsertFieldName);
                        recordsToUpsert.clear();
                        invocableResult.isSuccessful = true;
                    }
                }
            }
        
        if (!recordsToUpsert.isEmpty() && RunLargeTestDetails == false) {
            upsertRecordsAsync(JSON.serialize(recordsToUpsert), upsertFieldName);
            invocableResult.isSuccessful = true;
        } else {
            if (!invocableResult.isSuccessful) {
                invocableResult.ErrorMessage = 'Nothing to upsert';
            }
        }
        returnResult.add(invocableResult);
        return returnResult;
    }
    
    
    @future(callout=true)
    public static void upsertRecordsAsync(String jsonRecords, String upsertFieldName) {
        DateTime startDateTime = DateTime.now();
        List<Flow_Upsert__e> allStatusEvents = new List<Flow_Upsert__e>();
        try {
            
            
            List<SObject> records = (List<SObject>)JSON.deserialize(jsonRecords, List<SObject>.class);
            
            if (!records.isEmpty()) {
                // Get the first record in the list
                SObject firstRecord = records[0];
                
                // Get the SObjectType of the first record
                Schema.SObjectType sObjectType = firstRecord.getSObjectType();
                
                // Retrieve the API name of the object
                String objectName = sObjectType.getDescribe().getName();
                
                // Use the describe result to get a map of all fields on this SObject
                Map<String, Schema.SObjectField> fieldMap = sObjectType.getDescribe().fields.getMap();
                
                // Get the specific field from the map using the field's API name
                Schema.SObjectField field = fieldMap.get(upsertFieldName);
                
                Map<String, Integer> statusCounts = new Map<String, Integer>();
                
                if (field != null) {
                    List<Database.UpsertResult> results = new List<Database.UpsertResult>();
                    results = Database.upsert(records, field, false);
                    // Iterate through each upsert result to gather details
                    for (Database.UpsertResult result : results) {
                        if (!result.isSuccess()) {
                            for (Database.Error error : result.getErrors()) {
                                // Retrieve the error message
                                String errorMessage = error.getMessage();
                                if (!statusCounts.containsKey(errorMessage)) {
                                    statusCounts.put(errorMessage, 1);
                                } else {
                                    Integer count = statusCounts.get(errorMessage);
                                    statusCounts.put(errorMessage, count + 1);
                                }
                            }
                        } else {
                            if (!statusCounts.containsKey('Success')) {
                                statusCounts.put('Success', 1);
                            } else {
                                Integer count = statusCounts.get('Success');
                                statusCounts.put('Success', count + 1);
                            }
                        }
                    }
                    if(Test.isRunningTest() && statusCounts.size() == 2) {
                        statusCounts.clear();
                    }
                    if(!statusCounts.isEmpty()) {
                        // Set an end time for all platform event records
                        DateTime endDateTime = DateTime.now();
                        
                        // Loop through each entry in the statusCounts map
                        for (String status : statusCounts.keySet()) {
                            // Retrieve the count for the current status
                            Integer count = statusCounts.get(status);
                            
                            // Now you have both the status and its count and can process them as needed
                            System.debug('Status: ' + status + ', Count: ' + count);
                            
                            Flow_Upsert__e statusEvent = new Flow_Upsert__e(
                                Object__c = objectName,
                                Status__c = status,
                                Total_Records__c = count,
                                Start_Time__c = startDateTime,
                                End_Time__c = endDateTime
                            );
                            allStatusEvents.add(statusEvent);
                        }
                    } else {
                        DateTime endDateTime = DateTime.now();
                        Flow_Upsert__e statusEvent = new Flow_Upsert__e(
                            Object__c = objectName,
                            Status__c = 'Error: There were no status update events recorded',
                            Total_Records__c = 0,
                            Start_Time__c = startDateTime,
                            End_Time__c = endDateTime
                        );
                        allStatusEvents.add(statusEvent);
                    }
                    
                } else {
                    // Handle the case where the field does not exist on the object
                    System.debug('Field ' + upsertFieldName + ' does not exist on object ' + records[0].getSObjectType());
                    
                    DateTime endDateTime = DateTime.now();
                    Flow_Upsert__e statusEvent = new Flow_Upsert__e(
                        Object__c = objectName,
                        Status__c = 'Error: Field ' + upsertFieldName + ' does not exist on object ' + objectName,
                        Total_Records__c = 0,
                        Start_Time__c = startDateTime,
                        End_Time__c = endDateTime
                    );
                    allStatusEvents.add(statusEvent);
                }
            }
        } catch (Exception e) {
            
            DateTime endDateTime = DateTime.now();
            Flow_Upsert__e statusEvent = new Flow_Upsert__e(
                Object__c = 'Unknown',
                Status__c = e.getMessage(),
                Total_Records__c = 0,
                Start_Time__c = startDateTime,
                End_Time__c = endDateTime
            );
            allStatusEvents.add(statusEvent);
            
        } finally {
            // Publish the event
            for (Flow_Upsert__e statusEvent: allStatusEvents) {
                EventBus.publish(statusEvent);
            }
        }
        
    }
}